# Generated by Django 3.2.16 on 2022-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=40)),
                ('address_2', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
